(package "un-mini"
         "0.2.1"
         "Automatically close minibuffer after it loses focus")

(website-url "https://github.com/jcs-legacy/un-mini")
(keywords "minibuffer")

(package-file "un-mini.el")

(script "test" "echo \"Error: no test specified\" && exit 1")
(source 'melpa)

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
